### ISSUE TITLE
 掘金后端迁移问题

### ISSUE THREAD

**Issue by DF-teenager** [xitu/Refactoring#1]
Android端整体数据穿越回一周半多（12天左右）前（主要是个人信息和我喜欢的文章）~ pc端部分数据穿越~   阅读过的文章只显示篇数进去之后显示没有阅读过文章，收藏集cell存在相反的问题~ 用户名：LHammer(13520245009)

**Comment by yikejiucai** [comment]
1. Android 端数据具体是指什么呢？
2. PC 端目前没有阅读过的文章的入口

**Comment by hanks-zyh** [comment]
安卓刚更新了最新版5.0，可以更新一下看看数据

**Comment by DF-teenager** [comment]
我用的就是5.0~ @hanks-zyh

**Comment by DF-teenager** [comment]
个人信息的备注（12天前的）；
关注量pc app端不统一；
我喜欢的文章少了一部分，大概是12天前的数据；
收藏集显示为0；
阅读过的文章显示没有；
动态里面显示n+1条文章加载失败； @achilleo

**Comment by huihongzhou** [comment]
手机账号：15170056168  提示需要重置密码，可惜这手机号已经注销无法接受验证码；能不能帮我绑定个邮箱 793989162@qq.com

**Comment by owen1190** [comment]
编辑以前的文章，会显示非法用户，视图查看他人文章
![image](https://user-images.githubusercontent.com/17617063/27523367-4d9dbb34-5a5f-11e7-9f8a-8dc67e335d0a.png)

**Comment by ShowJoy-com** [comment]
编辑刚发的文章 提示如下： 
![image](https://user-images.githubusercontent.com/19988230/27525946-c825433a-5a74-11e7-98c4-f85dfa807331.png)

并且消息推送好像也有问题

**Comment by linxiaowu66** [comment]
@achilleo 我的问题也是同 @DF-teenager  一样， 所有的动态都没有，停留在12天之前的

关注量pc app端不统一；
文章喜欢数也是不一致

**Comment by sidyangx** [comment]
@huihongzhou 你好，已安排开发给你修改。

**Comment by sidyangx** [comment]
@DF-teenager 你的问题是否得到解决？

**Comment by sidyangx** [comment]
@owen1190 非法用户这个是否还存在？

**Comment by sidyangx** [comment]
@ShowJoy-com 试图查看他人这个是否还复现？

**Comment by sidyangx** [comment]
@linxiaowu66 是否升级到最新版本的掘金 5.0.1

**Comment by owen1190** [comment]
@YangXinlin 已修复了

**Comment by DF-teenager** [comment]
基本解决     就是收藏集显示为0  点击进去有~   还有就是阅读过的文章只显示一部分

**Comment by DF-teenager** [comment]
基本解决 就是收藏集显示为0 点击进去有~ 还有就是阅读过的文章只显示一部分 @YangXinlin
