### ISSUE TITLE
评论功能无法点开以及评论显示数量不对

### ISSUE THREAD

**Issue by threadshare** [xitu/Refactoring#10]
再反馈个bug[调皮]:我看了几篇文章有一个想评论，然后点击评论没反应，然后评论上面显示的有几条评论好像点击也不管用，之后又看了其他文章，能点开但是和上面写的评论数不一样（原谅我看文章必看评论的坏习惯）

**Comment by sidyangx** [comment]
你好，请提供具体的无法查看评论的文章地址，我们来复现一下问题

**Comment by threadshare** [comment]
没有了，我刚看了一下那篇无法评论的文章，现在直接跳转到github界面了，那个评论的内容直接在github上面评论就可以，还有另一篇的评论已经正常了。我读的最近几篇都没有什么问题，等我发现了问题，然后再提issue吧

**Comment by sidyangx** [comment]
@GiggleAll 收到，感谢你的反馈
