### ISSUE TITLE
文章点赞数是点赞者头像数的两倍

### ISSUE THREAD

**Issue by kalasoo** [xitu/Refactoring#12]
### 问题描述 （必需）

点赞数是点赞者头像数的两倍

每一篇文章

### 涉及的端 （必需）

- [x] Web

### 环境信息 （必需）

网站端

#### 浏览器 UA

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`

### 是否必现 （必需）

- [x] 是
- [ ] 否

### 复现步骤 （必需）

每次打开都会有

### 截图

![](https://ooo.0o0.ooo/2017/06/28/59536e598320d.png)
![](https://ooo.0o0.ooo/2017/06/28/59536e596ee94.png)

**Comment by sidyangx** [comment]
这个问题已修复
