### ISSUE TITLE
ios app首页特别展示问题

### ISSUE THREAD

**Issue by jjeejj** [xitu/Refactoring#13]
### 问题描述 （必需）

ios app 首页顶部的特别展示，选择完后，当时是没有问题的。后台把运行的app杀死后，再进入首页后，特别展示就回复成两个最初始的了

### 涉及的端 （必需）

- [ ] Android
- [x ] iOS
- [ ] Web

#### 掘金客户端版本号
5.0.1

#### 手机系统及版本
iphone7p

### 是否必现 （必需）

- [ x] 是
- [ ] 否

### 复现步骤 （必需）
ios app 首页顶部的特别展示，选择完后,
后台把运行的app杀死后
特别展示就回复成两个最初始的了

**Comment by sidyangx** [comment]
你好这个问题我们已收到并记录，开发者会按钮优先级来修复。
