### ISSUE TITLE
android app首页特别展示混乱问题

### ISSUE THREAD

**Issue by hrygddv** [xitu/Refactoring#15]
### 问题描述 （必需）
打开app后讲首页特别展示调整顺序，每一个分类的内容不会变化，依旧保持未调整顺序之前那样排列，下拉刷新也不会调整回来。例如，将“后端”和“产品”的顺序互换后，“后端”页面还是“产品”的内容，下拉刷新也没用。

### 涉及的端 （必需）

- [x] Android
- [ ] iOS
- [ ] Web

### 环境信息 （必需）

掘金版本：5.0.1
OS版本：Android 6.0.1

#### 掘金客户端版本号

5.0.1

#### 手机系统及版本

Nexus 6p 
Android 6.0.1

#### 浏览器 UA

Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6P Build/MTC20L) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36

### 是否必现 （必需）

- [x] 是
- [ ] 否

### 复现步骤 （必需）

如问题描述所述

### 账号信息

hryg

**Comment by hanks-zyh** [comment]
@hryg 收到，我们已经修复，下个版本就好了
