### ISSUE TITLE
文章分页加载有问题

### ISSUE THREAD

**Issue by Sapphire2k** [xitu/Refactoring#18]
### 涉及的端 （必需）

- [ ] Android
- [ ] iOS
- [x] Web

#### 浏览器 UA

Chrome v60

### 是否必现 （必需）

- [x] 是
- [ ] 否

### 复现步骤 （必需）
比如 首页 下拉到 出发 分页加载的时候，原本最后一篇文章，会在加载完成后 滚动到最上面（看不见的视区）也就是不在视线范围内

**Comment by MopTym** [comment]
已修正
