### ISSUE TITLE
掘金文章各种数据不同步

### ISSUE THREAD

**Issue by linxiaowu66** [xitu/Refactoring#2]
下面这篇文章：
https://juejin.im/entry/594b6b688d6d810057ddd2d8/detail
评论也都是不同步，别人账户看到的评论我自己反而看不到。
喜欢数目在不同的用户下展示的都不一样，同时我的关注者个数也都很奇怪 不同的用户看到的都是不同的， 这是我的用户ID： 小兀666

**Comment by sidyangx** [comment]
你好，这部分数据同步的问题，我们正在修复哦

**Comment by sidyangx** [comment]
@linxiaowu66 评论和关注者部分是否复现？

**Comment by linxiaowu66** [comment]
@YangXinlin 文章的喜欢数貌似被你们给截断了，之前和现在的不一致 估计你们是取某个时间点截止的吧
