### ISSUE TITLE
某篇文章详情页无法查看

### ISSUE THREAD

**Issue by wyycode** [xitu/Refactoring#22]
### 问题描述 （必需）
https://juejin.im/post/5957b0aff265da6c3f70a592 这个链接打开报 data created failed错误，无法查看文章。

### 涉及的端 （必需）

- [ ] Android
- [ ] iOS
- [x ] Web

### 环境信息 （必需）

chrome  57.0.2987.133

#### 浏览器 UA

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

### 是否必现 （必需）

- [x ] 是
- [ ] 否

### 复现步骤 （必需）
直接访问 https://juejin.im/post/5957b0aff265da6c3f70a592

### 截图
![image](https://user-images.githubusercontent.com/7800044/27845330-f94d1cba-6160-11e7-9a64-e827445b69c9.png)

### 控制台报错信息

app.76a1bf7….js:1 Error: data create failed
    at c (app.76a1bf7….js:1)
    at other (app.76a1bf7….js:1)
    at app.76a1bf7….js:1
o @ app.76a1bf7….js:1
(anonymous) @ 2.232c162….js:1
app.76a1bf7….js:1 [request failed] 200 GET https://post-storage-api-ms.juejin.im/v1/getDetailData?uid=57b15c53165abd00…XJlX2luIjo2MDQ4MDB9&src=web&type=entryView&postId=5957b0aff265da6c3f70a592 {"s":4,"m":"data create failed","d":[]}
a @ app.76a1bf7….js:1
(anonymous) @ app.76a1bf7….js:1

**Comment by sidyangx** [comment]
你好，问题已反馈给开发

**Comment by sidyangx** [comment]
@wyycode 我们开发已经解决了这个问题，并且我复查已经 OK，这个 issue 就先 close 了
