### ISSUE TITLE
Android状态栏颜色问题

### ISSUE THREAD

**Issue by Brook007** [xitu/Refactoring#28]
### 问题描述 （必需）
在MIUI9，Android7.0上面，掘金阅读文章的时候，状态栏是白色的，状态栏背景也是白色的，以至于状态栏一片白

### 涉及的端 （必需）

- [x] Android
- [ ] iOS
- [ ] Web

### 环境信息 （必需）
Android7.0 MIUI9 内测版

### 是否必现 （必需）

- [x] 是
- [ ] 否

### 复现步骤 （必需）

打开就能看得到

**Comment by hanks-zyh** [comment]
@Brook007 你好，问题已修复，下版本会更正
