### ISSUE TITLE
Android 端点击广告出现的闪退问题

### ISSUE THREAD

**Issue by changkun** [xitu/Refactoring#33]
### 问题描述 （必需）

当点击安卓端首页的 ListView 中的广告 Cell 时，触发闪退。

### 涉及的端 （必需）

- [x] Android
- [ ] iOS
- [ ] Web

#### 掘金客户端版本号

- 掘金 5.0.12 
- 从 MIUI 应用市场下载

#### 手机系统及版本

手机系统：MIUI 8.5.4.0
Android 版本：6.0.1

#### 浏览器 UA

Mozilla/5.0 (Linux; Android 6.0.1; Mi Note 2 Build/MXB48T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.116 Mobile Safari/537.36

### 是否必现 （必需）

- [x] 是
- [ ] 否

### 复现步骤 （必需）

同问题描述。

### 截图

例如当点击图中的 Momenta 广告时，出现闪退。

![wechatimg8](https://user-images.githubusercontent.com/5498964/30637806-04731326-9e2c-11e7-9d85-43bcf1dcf01e.jpeg)

**Comment by kingideayou** [comment]
目前最新版是 5.1.0，可以下载试一下
请问是否从应用市场更新了 WebView ？如果更新了 WebView，建议卸载

**Comment by changkun** [comment]
@kingideayou 更新后此问题已不再现，WebView 是从 Google Play 自动更新的，与目前 5.1.0 版本尚未发现冲突。
