### ISSUE TITLE
网站登录提示 401 错误

### ISSUE THREAD

**Issue by IAMJ** [xitu/Refactoring#4]
网址：https://juejin.im

![juejin](https://user-images.githubusercontent.com/2928760/27573689-a8232a26-5b45-11e7-818b-e4ac2c04b97e.png)

在 APP 登录没问题

**Comment by annata** [comment]
我也有这个问题，登录不了 。而且用邮箱重置密码也重置不了

**Comment by sidyangx** [comment]
你遇到的问题已转给开发人员

**Comment by MopTym** [comment]
@IAMJ APP 最近发了新版，请问您用的是最新版本吗？请打开以上请求的 Preview 页给我们请求结果以及您的个人主页地址以便查找具体问题

**Comment by MopTym** [comment]
@annata 重置不了是有提示邮件发送失败还是邮箱收不到邮件？

**Comment by annata** [comment]
@MopTym 能收到邮件，也能打开重置页面，但是在重装页面输入密码以后点重置没有反应

**Comment by annata** [comment]
@MopTym 额，有反应，页面显示的是 { "missing": [], "illegal": "new_password" }
这么一个东西

**Comment by annata** [comment]
@MopTym 重置密码的api调用返回的是  {"s":4,"m":{"missing":[],"illegal":"new_password"},"d":[]}

**Comment by MopTym** [comment]
@annata 密码有几个字符？

**Comment by annata** [comment]
@MopTym 63个字符。好像没有任何提示限制密码字符数量或者类型的提示啊

**Comment by MopTym** [comment]
@annata 接口给出的限制是 30 字符以内，后继我们会优化提示

**Comment by annata** [comment]
@MopTym 好不合理啊，密码为啥要限制只有30字符。。。你要限制限制个255也就算了，以前的密码都怎么办啊

**Comment by IAMJ** [comment]
@MopTym 
在 APP 登录没问题，跟 APP 是不是最新版没关系吧？所以这个跟密码对错应该没有关系。
我反馈的是在网站登录 401，Preview 页没有结果


![jue](https://user-images.githubusercontent.com/2928760/27622625-d5316224-5c0a-11e7-8791-5db06c9b8931.png)

**Comment by IAMJ** [comment]
@MopTym 

刚更新到 iOS 5.0.1 ，也提示密码错误了，用邮件重置了密码，现在网站和 APP 都可以登录了，这个问题可以关闭。
昨天在网站通过邮件重置密码是重置不了的。
还有为什么密码现在要限制长度为 30 位，我原来的密码是 50 位，有点不太明白。

**Comment by sidyangx** [comment]
@IAMJ 你好，我们正在修改长度，将改为 128 位，感谢反馈。
