### ISSUE TITLE
个人账户不对

### ISSUE THREAD

**Issue by icepy** [xitu/Refactoring#5]
一直使用微博登录，今天发现登录上去之前，不是我这个 [https://juejin.im/user/56d08dcfdf0eea79dc943244](https://juejin.im/user/56d08dcfdf0eea79dc943244) ，已经无法登录了，是别人的账户。

**Comment by sidyangx** [comment]
你好，如果用你的微博登陆的不是这个 https://juejin.im/user/56d08dcfdf0eea79dc943244 账号，那登陆的是哪个账号，可以提供一下地址，我们锁定一下问题

**Comment by icepy** [comment]
已修复。

**Comment by sidyangx** [comment]
收到
