### ISSUE TITLE
未登录时页面有数据，登录后页面无数据

### ISSUE THREAD

**Issue by zyunv5** [xitu/Refactoring#6]
chrome下报错
火狐没问题
IE一直在loading中
未登录前，各种帖子都能看到
登录后，页面上没有帖子，只剩基本骨架
F12 报错
Request has been terminated
Timeout of 20000ms exceeded

**Comment by sidyangx** [comment]
你好，你的问题已转给前端人员

**Comment by MopTym** [comment]
Chrome 的报错是接口问题，后端会尽快解决。请问您使用的 IE 是哪个版本？

**Comment by zyunv5** [comment]
win7的IE11 现在好了~
估计是启用了最新版的chrome...
chrome版本目前是59.0.3071.115（总感觉它要搞事情）
