### ISSUE TITLE
账户无法登录，找回密码显示该邮箱为注册账号~~~

### ISSUE THREAD

**Issue by saintaugustinus** [xitu/Refactoring#8]

**Comment by sidyangx** [comment]
请截屏哦

**Comment by yikejiucai** [comment]
麻烦提供一下邮箱

**Comment by saintaugustinus** [comment]
具体那个邮箱不记得了，我的常用邮箱都试过了
lenderclvt # gmail.com（已用邮箱重新注册）
saintaugustinus # gmail.com
只记得ID: saintaugustinus
我确定我注册了

**Comment by sidyangx** [comment]
你是这两天注册的吗？
在我们后台看到 lenderclvt # gmail.com 是刚注册的账号
saintaugustinus # gmail.com 没有找到有注册过账号
确实有一个用户是 saintaugustinus，但这个用户用微博登陆的
