### ISSUE TITLE
登录的方式不对？

### ISSUE THREAD

**Issue by leeboya** [xitu/Refactoring#9]
我记得以前第三方登录可以用QQ，现在没有了 ，现在按照提示重置密码以后发现收藏夹已经什么都没有了，这种操作把我绕晕了，我是换了一个新账号还是数据不见了？

**Comment by sidyangx** [comment]
你好，掘金从来没有 QQ 登陆哦，只有微信、Github、微博这三个第三方登陆方式，除此之外就是邮箱和手机。

**Comment by leeboya** [comment]
喔，不好意思，搞混了，想成segmentfault了。
